insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Australia', 'AU');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Canada', 'CA');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'France', 'FR');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Hong Kong', 'HK');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Iceland', 'IC');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Japan', 'JP');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Nepal', 'NP');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Russian Federation', 'RU');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Sweden', 'SE');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'Switzerland', 'CH');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'United Kingdom', 'GB');
insert into country (id, name, code_name) values (hibernate_sequence.nextval, 'United States', 'US' );